---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB9vZLntJxyNTE30RUIR1kIUDEEFLznA0PfKh31kHsr/W371YfgjRFYtQ4ry5FTMLx8xoOABzZH4kY2H/21HAHSW7vBWk/fyCXExuYNZeaJhC3baPY95ZaPuS6qAjWJTgLUFTK4TR6OtxrCw8s5OYspOqV4o2WGmRCktYmQJZx6uZxzJ+W7TZ7nRtrLNWsTlLZmvpBtj96t2a3A7z0+BlvvonL1eJh6CyboPF4LJJ86JPUPbzP1OQW9udQgr+IwbcOfBWkR1uWJ4VyD7DpB8obJkLLeqaNG2CngEWNKmeGZBaCt5HwfUb5efMje0ZH6hlSUPsHYNW79VBl9YzmpbIIMvI1K1kXjdRdcCLA0m3p6bsBAiCnWcCUVXrSWyEZ4S4683ehb6Ou+R6y0OPIlKF+EXfzgD8iG2g1PcpsCRb7e9lqQiLHdLld7azlFEtay2wcfAvoMjXOoQZ+5ufmzOw+93CbVq6VCcsyJer0TSUyhyqDCIbY3Ivz/TKsFJYFMGQX0hf5QI1CzQsOZkAQ/bHX7lMdO6X7k5zJtbXdWwLmdMqaaeJU6FWPk0VUpKTGF2ogjuGRceAKR1nSWqgVT4M01iMoRK3hyxN/uN6A7wGhH2SaYC95GJeWM2p4n5L5ZJJ+GQQgNdd1bTGE0a1K/rQEW1FnOD0wYJ4cDLkHKBuwjZ6jz2dEPjLnGDBrqq3sE6n+9X1V4oNz+9CgaYW1b/wgjbRUpUqYqRBNTcNuORA/P31HvKykwNa6TVwLqIT89D0kKHWxXKQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
