---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgBiKBV1bG6klB1RJNikySLLTJSrL2cq8fR+FEaVtkI+XoZZzUmZRF7TMPYz0jMgKzJX2A9lcnpeioA5JPvSyXqda3/jKGa2nxdr+/13t7MGlw54VAfVwxbYMBzmZvUGegIUUGLXHb7tiD3q6njOxjQPCGQUqHchnAZ0W8b5pDQwLLbMlwb+5SMpod6gZcpaMaqXvIbffnzQAQU8y+pr3PpcNedBLPqrFaZgx/bxOrstOZh7ga+h0xwPbs/1cGP93i5S2PiIyNXg9vyLo5OoGiZE6ryf1fLhShfZc8JnPiS9873Fc23OPztFyq5nGweRbYELwkRLpLPV3vj4E8cHboTePBncX0SNUcpqaids4YmNX3d0NX5wZS7cVfXZwbFHTASiDHYawImnDlbwGMRu36xmQAB9E44IrVJrkBHecwZTunpSLu0bbix6GgUPKEmfTvK/r301NXbCIbY+tOmUxW5QhtOW3NFr0/NXLqkcGSAaym1d5fGlUvTE80+TOOnX+J9UXO6tNWcC1WQT2qprRcUBDcsyrl+ckVuj1CvxpwnrKDjz9cuXUIHHQkMmzFX84/6Cdp834Ga9znx+HNf9GaKIBTdWxSh7GOcE0Yqo7NYMqxEKAoRiY/auQOf9vU3exDCheQZ/4K7TaGaMk6yYzyDC7Ej4ltJchlQvmv4HQfm1fOpfg2hPbxDMOejlEp3T0x/WP2dpfKxe
    AUTHENTIK_EMAIL__USERNAME: AgAQsQgxWLRS6dydWlKACJnwECI/VMdHhKKiD6ZbXnRPccCkorW3S6DvnPQW0foWShCxxU/HM2MoBgG23IC2fr8ImxfmpZ9C7tQJUW0/+CNRXb40h7yTxEcf5cdw93I9i5kAqibz4X65CmhFXVPSrS3K0tHHioM4EKm1gK9RAU5oD+O9vhqrdgGDEy7O1zUW7V1JFlHL7XqAg3O0auYVdR0qmuNhZIcOg0nHlPrwSZct4ep9SyYi7gB6fshNUrBVFYBkLo6LodAB1NWtDzThpVDB8lIK26Jfe2T+5gDTdxfGwonMBVmo872A6Rrvq9SuPqO+68wmmSs7CRjExcK0Ui0aZcQm+QoecpogqDYF+gVPbxIgOx5Q2Rsah/stMqM+kH5Cnuc4vXtIBK1w5syzOPOsNNhzgO5nXgtanyxeSHnu/4JxMbeckB3JYVI9NR4XsDENpnNCw0ITpS9OOGiIhSXTUPzv8CYV2eVd+AiHByxKOVIFv4XqYVIWGAmyvjAArINN4zJzpgjnjE+WKLFaCZRvkWOR09L+pLyDoFtGzHYw4Y1/w4qw0pCOikOqbUKY9PYcO6K6v8Up9VZiC7ILMHzDbOklN820zzcDYPPiQfDPshja84hK+X0E2PdAaed9+pCHkNP1nbp4w6z8aSnEdveJw6Yvh6ZngwyJvxvlcM2Sj3hdmgiU+AnPBWEc+bm+geKkuS2G8Te7W6/rqPeM++KP/VCp
  template:
    metadata:
      name: smtp-credentials
      namespace: authentik
