---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgBe04fV6u1IcjvJWwwyyvGq5IijFPwHGIHiPmKDdyJDo3Cs3LSPigII/F/bfdcfhbCe6+rFYfoKQXFBgszvBUMe2KglwWaWRk0TxhM3piCSHkI/E1srUjmdmcrsj8oSmcD134vE8/HxiP/N3Hwv8ev//0p8RASPmAWn6i47rPw5XPRwMF2ONRyhVa++7+sy/wPGmk7lLbujUqKt8V7BpgIvO8CCmORb47DOP/sxiuIYkOqJgo6Dkpd7C++1nUukOvOdaIK4iw7Y3/35rjnmIzZTELZ+zFETUaGergESB7VQZBMavLDmYpgcGJl1BNtNNgS1BExMU72IS4BgJbRUpmdtWlm9caAW5CiWKt78bEgG/l1uDzscUC9xgwvogLxIvARIfxIpVY0vcwyaIJWAIkaXg6hkj1XK68Itsox0loABtBQO2+QjcyGHqn2MitrZkwZrCEfBsywv8+WXQ0aqtWsxBnZii1csU2JAGSMBozr78YbXUVxDRarVJ1A89lVL2ViJa1tyzTm/tpRYLhvkGAt7qzNTApT8waOrteJRA1YpPB033YrOroChbeUv/CDE69IftNX+WQyGy0OsvBnV/6n4g2UnewaHhAXvvdtNU2cCY/5uTCpGPJSUFZzJNSzgJtGzBict9hsn8c8BpLcg50pS+rKPJhNiGefGLusy/DebgsHh2jAbBOi4hkrcaHUlzyRYlCcx/VEl1Q6HOpcemRvSTxVA
    AUTHENTIK_EMAIL__USERNAME: AgBVpEEuZH8+98qDBJ2giGDlZhInagrLGR4JFc2GbvlsqB7SOmcAVcV7jlltMJYo4vnVjhUf3F2IWIkSWr08/7dOI3gq0h2MQEFdGtY7WHWT6TPOKmjXa/pe14/4u5lm6VEGvSGq0FdpCTvHPv40tEu3vd4NXbg8a1sn0yihQqFLphWWB29nyeDojCV7L7tavmQZrkfwf90N3LOba2a7PSELSfFEEE8B1/petYKbtggdYJ9fO6fR3V2QAVEx3Dyt4o4ZZ8i4P8qSrYwmvOVB8p+PzTQ3IbR4uL5TjmHARjZsRhZw9SeflbFWiqifK35IlaLMjQDpIobHmS0zz/xLFfUIfLbUAQlN0ypkeuUSZ1egd2sEo9ONN1EREwr6QX5/yToJ4X2NkU7PbURr4xdYynWQSBALb2W+KemAGb5khmtknkFTCNWePdgJ+BXDtNnHc/dWvcyCdFNJGOJEmO4mkeX9YlC0TqtMkrmI1sqL/PChpL3k0Svaaz6NZl1BmDP6BgbR/7DPSV3Ae6Fx7h+apvXFYHjCNNte0/e0K2mtn54i5CUjhesFI1KLsPbFlkeUfEPPNM25gE6Y3gIuf7vKdMNut5hVNxIoi16tXOedfP8x3OGG0wVyd9peu5S3i8P3xqUT+2esaS8jyN1If1InnYn7vOvbYsrEMNteYUug+yOtFVHXH5RVxV5rSI8DiDmT/JgC7M0IYartUSJlT4aoOCx5edyanIhcPfy64mWuQ5zh
  template:
    metadata:
      name: smtp-credentials
      namespace: authentik
