---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgCHLVss7w9e8oUdGvf/gy6QnyzyTkZAj/Mb8kfcNIoILNK5w8lYSe6nLuIkbTLgB9B4NCH69fFBrDbjY16oTMXy83XppzDtpTAXwdKRX/8WLt+7xDe3Km1Ygf+ZrjAlhmdGfHygNga8xP3Y2WmR3MA61A0zbOYADP3vxqjxE1SqxjGxCUE3+bdEKRJzyATi1XdDeEhAAN3l1fBCr8c3o/E2ILvT/aniSLgu3C8QHZlyzggzBB3A7eAkPZhyC0dPkAHNe9CtrUI5oE0FPRLSncFhX02kaCj4NC+kpi7WC0XS5c/IR4y6Go4iVLURE3VxWAzKG4KD7dSJXsQM6CVSCVPCmIvvNXh22VSR1JfHFnr5T21UnhjYtQp12lnyb7I4qOam6OfrnmSn07X+VBn9w8bujscs2EJjbwHyoALuxOHSPKWX9uJJwtVdOwonf08GclEEWpJSEgS9yvUhc74KSny0Tse6fntzGfHa1OvYQjlEdGfoMUOxwNpymd9pS0vCUYY5bmPb27RSjBFf1awyYofxYV35BqIniXlutXFRjDR+2nMtDJuaEsAO1wu1UcFCgBArsPLr+7W9mzRcGhW1Sh0eTzP8+SZXmcFz9ORKAfLCn7iviGwmWwnL3O5zeYfFMKhl1htU3FeM/XRP+p+aNnqMqe5Yl0R4gJSkKNLPnIY1Yax6j03UmTxFt+52gFmQ6NPa998w5k4prstxMIW4rlIT2JfZvGmJ7/DxDTWKxQHbhg==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBYxBIaYrtBOkP7IgDXJSx44Ydvw76ywQhI/aA8y/o0gH1Z2GfT057gARTHd4+Brod1hS1pvOIqfjT0iC1oFWJx0CQ2yD3g1IdBvAMZY09XK9hzwbJ05NGWL4Q4d8oVKKx2ylVhWAR32MriUOH4ex76TwVbM7Y7dVQExnfWu/U7YHVHOmAqppRVtGiMgN5CbnVLjOfYI3JNkoo7gDNYR+bEpl4Xa5BLD5KqIYSytq+kiwL02Y5jawIUcNRsScAE2xLeca3iRkCN07cYDJ7zsUpJV7gfvf0y9F9Q9kEY+p7ZJN/kmA4loobRZ1PyLw9qVG078rSrSfDIGECHvyF4WUGOwqf7PoqZUgBM6LjU6e7ultrPCNVdVDjeoRaO1X7/FS9f5Vo8Gza7iSuEwetLTIkt/IKhrRvNqf0Bn/7zzHJKUFa+eGAmABRmPmdG65IV0NnOMLo7NkkwBLvHIZ8dFaGjBG6kVeTxJVAcXMXswVduahIKXLhaGzL4SxQsYgc/cbKswCidGNYgGRluQixr9raP7KsU1i0u//EKnFnNRng/sMzcJuYsjhTQHYUCSVF38+C/BkdbmaE02BauOZI0Rvfk+Udt2lOKhErSuFxwrRQR2cgu+5gis7hbfvHIIVYk3njLbEf7//oMYZOBxAyNXwlQ+R1GO94DU8K5v1UNCqu0C3wfZKIzFw6Fcm/pDSxv6eUciRgRopXPZrH4cmivJKwLNHqp9dM9KP5fVt9/MqNbmg==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
