---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava
  namespace: monitoring
spec:
  encryptedData:
    STRAVA_CLIENT_SECRET: AgAUiRTPF8DLooPEFT7v4Xa86h19UGAd6HNSDXuZXoCCUdO/G5ZKPl1zaNMa61+Mqu/qAtm6YcBd7YO3rVt85EIknF9+ij6Nu9hDGslSFLH0uMJZKh4YlD983i6Z0HXjoVO7C7EX3t5CKYcouc7FnJQDhUd7UdKA/rdPo2MkL45BEWXfna7psxkuY9E7+9M5PkaycKRG7E7Duk1t7fUQg1I3ziY+NFovbvSsSu6Grg7IudpA9DWvyMFJHWf1zYt3B7TEY6dHXquBiG0GzgNGwjtpPRv8zh2rRCZ2A9WINAd/KNrC0jvtifBOth3Ed8qv+NT2YG1eiO7bhjjNSv23Utd2pKmOjAZJnZ8IDjTqwsY9vYYnqqztaM4yknW1yPpsd497mZcF0w+gqSw++Mucq1XhEwoqSOroa+g0F2sRhkRfmSt+0bKvRNF9JFyJeRlrR2BKRQ5JnWZ79GCLpzHm878hVQjC8c8tcFfQZt5a4o9PEKlYsfKL5P/4D+Wo2VXNNT6ri+7LLmitxxWaQgU+YzglCzwE9PnqTiRS6nEkhvhC6bWwoNT4+ths8HwMMcL7M/Er9Rwt3xtGuNuQaRyi4IXXXI0tuTJBY/obvHSkBfBzQDb4ev3P9cVwp44g0+bj06uICYm4PFk0krtBJPouC32pBZ+xI2wMVtYRmSWAkxtXsQNca49stGhrg+HNhsTrJofK
    STRAVA_REFRESH_TOKEN: AgCztStXEIXNcMbPnekhD7lShATgTBDiHU0u73Tu1SngLTnbjxC1qB9bkpAmLlBriPDgfrmsTa5M3lsQH1U+NXCbGYwGNWIiPkjLDcUlFd5+UjG6udnNKnwRojSHIHGFWcKXqmQy73PtPEuR+TRiTj23pGlh3wVrw0+9kp3yB9fMsY6MbJZRKR7Hj+oJJeYvPN3d1O3FBN9wbATbvkTzsy5m2r9ThkDOGpINyzaP+lmUpph+vXpwc0epQ5Amuo8OqV11lR+9Dr5JZx/BLyguLtqIEdymYZ/nDblSxReAkl0Sr2YcPD+BzrZ63mq8SzdaqK5rnOJSGNyR+iojuQQ+l75LF3IDsHKVvTgdX3yJyO7y1MvD9Z9uLzFyDddgpAScbdiYH8boFSwqoIM9mXVPqSDICpezbKgGa9uBzNQXleMZ6C554OEy/REB0ccJsq0Znls/sN6cCJjf/0lIWIC9H6pVJV4jPCQ4W0t6Any9Q3VsAIIh/v8vZlFF8/5MHN7Enw4/wtP6WM7l/Eu4Mzxcg3xkjKyHKG4KQOOKaOhTIHSgL8J+QLuD/szTNXvqBMLPILZ23ltMxalvHfEQgLWkXW/u3cDo/gEZwBci+nDA3Q4MU1We6hfIyzT0A7xMS1g03AE/xZVkdv7e2uaiXSD2GTaX20CFcGPZjJMmY8Q6BSGqKzpyps9xKvIfB3t0owAokFu8
  template:
    metadata:
      name: grafana-strava
      namespace: monitoring
