---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava-2
  namespace: monitoring
spec:
  encryptedData:
    STRAVA2_CLIENT_SECRET: AgCr5a48mSVf0j3kwqBNoTRur1GFWWHa74CJCdTe1wkT0iHsxFQAihIoZ5omLBUD/tqEggz0RwOR+7w/v9YjrbpjpV81IT4pXqaC7mwCOxVOpclcW6mCiWHoiyPWmYO357TgAPNe4ZfL6CaqdH2ayFI51S6S5eT6FYhsOlgmG55eZk1ijmWeC9PhY9T7ww+rJiWqY9IkSvktNijNZ00i23ltltmjocNiOLMAm/HURHnUA73Yj+8DpU+zBBYxfeqgs+irQ7xoPnJM6WJB3IrWLzjy+dQwGKFxcW50VPr62FYE2tAvJW41J7NovIIHQX8e2SVLsMAVb2armbW3JLyc3IJHedx6J1ShPm4QRJKTuxBDI2vGzrqhEJ2fbrAXqQE/2CXTCbuzxW4x32KyewvOIX4Qfo5n76agnu/lyhtotisaSuiiiukHB5n+WfXKi9tf3lvPdVHMdoGzxWTLXs5MzhDo3Cr55SkQDB9mtaP3YIAZV3WDMiN10Izkpj3uG3x7cA+/TOfCdxVkTOnKfpcWhTOCreN571G98QQcm/aoXA5wHjOakRvSgVI9xWALRWIK9ZZNG5FjeV27NyeLoe+NzZj+hy4ZQTntkntmhuMZUk2lYPUTulNEeGAsEdA/mrNDwNt2mDSfcwRF5X/IATH1i2NZJD+yf7KnwkK5Ocff+T+37YReUZK8C5RfS+ainCDZNfEB
    STRAVA2_REFRESH_TOKEN: AgC1qmm4MzZ7kaK9FfGT7VvoFdkSmj8F+tul32jr5yHASfZC7FpMI3P6RRD1PFhVD93WDIeekNF5uk2/9UXLwdtZ/Vs8i6/2/cDA7XPhqS4m/JyEsns8sCB4JfAHQ5TXxxLdgN4kM3wjfGbfhhJA5ShnBaxM1K3EF3h+t3aJw3GtNRujjMPHJd7AJRZIUZr/HYYdY0uqZuvHSeC0+rVnDUU5GNAoT2wo3uEL1zHNcYGptmwsWGHVjKBwX31bbWvbKvDk8z2FYNXw2ymMCGTiPSlwmsD4HQjMQVruY6qz5i9GbBoM3UwO2Q1lqQAB6IQULiWGAZYkfw6mOWk+c/3hinxL57x/xUJOmKhIffaRzI1sDJzEwFMWrhnnnOmoJu2PXQYGD54hjKgSLCOOcM8vzpG4XZ9hwiRosdeMNfKh4olLwEKwjqTUa4jLZt0r4M9G62B+LHmnvff4f6GMjqvkxpY7wcDanx0yiDgMjuhWTjCzAIrZ7KDD7uxnbIj+EX/UXXAbxfzssr30hz1MnMZlkj8WxB42ufxvvcMbxmM2BmgHZ/MD1Re/zFqdhBSyWTzdxb1/jA5nbZEwVMOyfeDoad6FYOdAaheZ6uPV6C9v9ECTEtG+HMvyPPRnd8u6o1kj+dRaRYHQr7mG7Lunp/bOwVOSz32WF56pAL7Mx+OzY2g9chjI0kfX94Z6P6Jf12ViGCMK
  template:
    metadata:
      name: grafana-strava-2
      namespace: monitoring
