---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    dex.authentik.clientID: AgCiZkI/upfm575FfA7kmC0l/chA2C+zeNOP0qnvLDv/rmRBI0ZyiCDwXirq1idjEyhqriDIeZvqTAZloxkex9MYf4cZNfCJZk8opeLsbGEYNlgjCpXy3F4At4PWIcVjjldkOY5ED/7QeQB9osPgzgGc1mofxHtvS79cbFyifVwQ6ExRUPstdzmoP49xBuDiX6g1S2J064T7Bt+reaqIGYfJKyYd0TjUOLEYW//ZWV7pQ+Jnx8kVeG6BTmntn5DzFd1S3nDnuNZ442I2VADmmn7cqFXmFw4AbU6UeyspjKGwZnbM30mlVunu8Kn+32/IR2G72fuom4q4iM47swnYTOiI9i9Kk4qiTV2ShOHqDj0zUx9UPFDqSMAcP4Ej1a4YNYwnxtDY+H++pIY8mQa6koWJMAC44mH3n8xkq3gJuAOdw4BmMxMGY7fbifZ62418T99pDksxaDJsvmdOGYwPARw0Dqm/72wdlvyfmfHprfcVAs24x23uzpb30uW5VQmK2Sat6KHXfDIuu8+Fy4FKfsR4r/Ikt2cTbCMO/DYQtDjTSA0alMrmfmq7cOKxzmoz5mXdxy3WjGo0mI1ieF6oq/Df7bblJ3f/SwBfiZr4GHknEYePY3asbhb85baCMtlbQYuTHgENbO5rtGlMrtNtCZrA6m6G3NO3BesSUZRDT+DD4GJ+5e58/OjLGemy0sgWtkQwD9tiUkRIS7SSqbmeTsP47XH9yq1494IHoE4EAV0OlQ==
    dex.authentik.clientSecret: AgByJj4ftXQGTf3mZCTT/EPkmzX9i5rlfHOuNDKj6in14788EbsAT5sDfJ4R3K4b06QztzZegX4XjIh28Iz+KJbZFsHCEiRLxLrKeEdREv9Mw8BQmul6UcLppZMdHWSJ7oxhoXslM4QUJdFPOPsg7H/QADM5vo5a1NDForcsgrJTM4ijCPzM1B5XxkmP2RZ2zEwu4pY8EUgPxPMWf22hDgLj2uOQnivRTa1pdPIlUUiO5jTGmI0b4GIdTZmidzl/GSkH7c2N/Zu5srcNd+JjSN7+zSDebKqnWLsxY1KoeiybrOvXQPiDZdtUdFGXL4ULxE6AZZPybN/Jz7CKsIRxoInhx66y8+4XTlRlwsUkLE1+ZxtBBQlaGPgPApiWnXqN8gfZx820D4pb3gWvM9DWN/jvoqqpb1LYlyycxtF/XhCQsyEHK7jFKvZGApxVOg9Navgqsu+RO0Wvte9y9ZHZ6ftKceaGwphBqoZPEW3UrBaRweOUytH4/vbbcoOIPyHHCZE4iM1q9byK8ejCQPSNxIAyGMqx2IQJ71QX2aDriu4rh6VsK1eFfUyngHQ6p2uzlubB4WLxn+FH7V6UvZpLB6V64LhdLcH6lNh1W0X5rU3ouoLBqgTX0OCTscL5so8D+efWabiSs8newmpWb8dxVjltJwaz8tTvk3kXKK84eFKCGrNgguSdpsQJCwm35vpCZP5rMAHBFItM/0IjLyJThzrxSlhUrq8BNbPqX75XON8unQ==
  template:
    metadata:
      name: argocd-oidc
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
