---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: barnes-biz
spec:
  encryptedData:
    SMTP_PASS: AgAfCRiJtgEsMb0BXT4qizMCyF76PslobN2YXiuyxbJYaPVAyzfqLA7r4F1+aXLJ5FiZt8nctfWXQoAbeo44NyI1i2XPEZudWAdEaAhIfWiQ9RtuQsS6vaAm8jlrl2S7QP0jf0I7kg7omBIqxTVp0l+pKERp0NJaLMa8XV4F3Kw6rkVm7f3CAXTfcRgPTEXsJfYi2xDJVR7Me8z0BymycNOW2u3Mk94I+nWbwx5SQGoByRKNaMfyBWUjByW7Ulek6omiMFNJSLcI/azVghjTXwJF7Hsbc1x5h5yWEb5pvEsMsU6qEv7UVArW1mO+IhRqvXm8Ymc4uz5072Viv23xWdYX/+owFoWTNSqTvo7AA1AR99bvxnds6QkvQxfv3RNTDo1ogRP3qR502hzQ5lo5J7Lesf6DlfCZn2v2NRpeP4gYTjlwRYl1lZ7ceYiVEBqarHMx3tbsMIGWiFCbKUY3FA+oPyt2x3XqFsIDcBAKbZj55Z821f2uNGMiuKcOwWmZxj7IM2XNJuuv9u4xjGDx4hbTZGuOmsPhM0vFn5zIVQ9taOTy6VTQWkbzqAaDNPGC+KvFKrKZsPWQ+aqzibvtLG/SecUp6jT67TRJnNBLk4px4zm6B4euII5bn1TMs5lBBmZDRZjeNiGt6KJ04G+Ia4aU2SdSxYrD9pzfLSIFRx3gixN4lIUfiKAs3fyvzgJVISAmPDdIEF/qo3037odU+FN8jGAx
    SMTP_USER: AgBFMVLNBRTI9Uzqt8MIsKqcRjNEtILwvAvIz43LoopW+5ywmBCrL51ZkunTtp8toK3Oa91IdmGK6wYfq7Tr8UZXTIQLLqinv0qUjtt1TyYlpkVHkr62Zxnm3sL5Hg1QkA+KksiHhBJ3SZVaCEWxX68R/m1ur+OAp6qRCsf5hfoALg/ZDPsVg7isy3knf/GFOcJfvvdX6WRXUPpIq8ItmyE3EtsmRVKvomAMYlvv0FTX9fOvDPibKLJE5kQ+ENM9kBPta+u5pU+r7iuobtEiwL/B2X7YNdcEd7WsJs55k0Q883u16Usmhomzcn6G0C00LUDKzmXBHRP/8inVRC/21z0DUul/XdhY687NXqg0gp5XH2YdNDxD9VjsJ8UaMG1WQd4pZeeOD9BNmY7jseILaPjSWxQHFqsxLsZI4tYCWEhk7UcjMjA5/yh5mXA8noUjhCJUTFzUoqWoifYLnDsJz2RrGaYWVXXWKIQE9cw7sSjBcYGpiee1jww0reZBR9lqMOyOnnw56okOq+98G3m0Coj5BTyrLpNxGx5oo5XwMEnTKj77CVu6z8vrTGib86/pop2yOMxJMzo7NbA0TM88uO6cVLhCE1rJJmkTiTRE+IIzUVaJS+t8GTbozTRJJxk2LUX8V9EkvzQ/BxQPNqTCjJVncddJZjb5PzlqDXrJwki4c5c5k3T28j1J8EoZnO8HrLccuW9sgdxGbKYT8hET7+0ft2rV2pG8fQ5NEga2YpaW
  template:
    metadata:
      name: smtp-credentials
      namespace: barnes-biz
