---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: barnes-biz
spec:
  encryptedData:
    SMTP_PASS: AgAdeOr9YmO9jn8YhabrqtdIxeb6f+cRFB3NZiQX1vcH6y4iUlfNzCVBcsqy9HPo+TOwwzoZpbg5zNirWZeEHjzxiuA21TCBkIeLJwgaKNKIstxXc6LYcGPXzkSJcxVry570GAlksa0bTyUYNakOAa+q7nINepw8zV0ZD/hJ4viSV7qiFcjxy22Wr5iLqqm7oHtj3y3GQpxdGsU7DC7bbi2wMN6tNYQSqtThYBB5dmGOcKU7/wpptRzKs8KQThuBwi0hkMCuxzp5E1n7S1ZCyP96f6cu19nNUE9hSMbMZBgC8WbyqVngctOwxwe23vVQt/QN+WCjSXpXG+XoQUha2KUJSFxU3kxJzglTtP9+N22nDlskC+gGAVozm95rxV7LKtNfAF5729dP1JTsdmobO56edYaKfdaXafw5v0d7CmUnEdMB+QMO6Vc/elhPIkH36jHVUKMfnoLw17sK9dA5KAOOx16foY8h0EsKJZeYjR3+C9UXS7651LRMnFmPNK1q6Tb7c1gJKpaJUGOx+47BpADLvokgbeBuHu3awR2jBFYQP3/N/RXVcLy5PbugKLbgpoGlnBzpUo5m4e/Offx62XERMrQ5rJ5/DtRm2XsDhyJZtXfTF/AoH8BwFDunO0MQq/KUl0UYxa8j5zsDRJ0WuOI/SV+TsOondcsDug2jxGsTmFNFverw9V1D+qgiqvhYAWDk4dsxkEwd
    SMTP_USER: AgAXdoQBpwtiMOUfR0c1N5nl5q55HDSvZEz/WWHe4MCnQtlaAnqc8ID9TLNqAaVxaZ+BP0p8YT8H5epgSG3WxtSEQFVhvzyTBkyjczY+wr1+eq1zEMXDsO1spnGiqJMuPKVS9H8KwgNiv2Bs2qll60exkOr2lX3r4oACUMsDSFKlsbXqm4XJ89lvFeznXf4m14Boih/Fsgptiv8UBsGC2Xpv21FEXnl0TJHZD0GsJEGnVzvZpI1EfApoIgUReoc5dOL/FgBVmFpUnu4FKa/zJYVqZGNuK6K7KoSpYLg9weDpbBh5Ar5rL38kzYTZr34xqJfUrOLgrkSmEc3alJfQnLnAULPOa2QIUk2Jwd0DXOTlqfMn06sr44nbXXqOMRlVHtk/VfwLI3NloGLWNWyFwtnjpo7OOc+7zNv2tGYedrsBlXuQ9TIz6dpgCX1CgClaEyApk1Mit4MUbxKoKpM7wUSEjYjJR/+pnigjdfdoyizk5bl1oV7V5o80RNL3EN1yx6iQOqzD1wLOmppPDyU8f3T+9uFmjaLaWCrCzMV5PSCwmfyUM2CT2ddUq3LrkeqjAUVNyPULl+VYYi/H7nXyf7YCZqGVhNchVgvPgBhA9UEACIwLUY6KmISE9eqydnLRrp3K7LhwtRpBbXz/P90lv8alLBPvnKZ0FpbpK4dbT5RCvHHAdQl13OAgQjjD5Koj3C9/8doFukeaxH244oTz+GDc8UO0
  template:
    metadata:
      name: smtp-credentials
      namespace: barnes-biz
