---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCaciIDR9fuGT17wU0lkWjdATyxB/dKhQjhR2bJiX1Tp+PMiIn4FHW87Q8Z/tmLrN2SXoJWwIZfzDQmCKOJuiU5m9a2UZwLqQZ4hvSa6jJjFpPR3ZU11chkdeE1+vf5jvTI8BTSsuIe5C4WGJLjbNlD+zLxWBszW2EvqoEOwnYV+xFq2I/C5mtp/m3k6o5tYKx7DPo7R5nFjVqqWRPjAISX2gQuD14+yrsuh9GpJM0DHA3y5tpPAKUXgba9eAlEcYPtto1gpMYnp4SK34HQeANFfjILMi4cVKbN8hgytHOsG0BjgqW7tQbDAD4WHyMAyAIEHdJj+vXrX1nM+UG3BgLMxOHjfoRFl2lsrJ4krJqkgu9nlOnvUEOh0BeV+vDFxbvfM9gYJUdq10Y1MAQGOHcDCU7lowZVhKKSPDHF7TN932uXpkfTWYLm0CDJ7NjH1yY8Ho+AwCFEGEwHnAx7hwoUjOV5/tLy6A5i5L20pirIBtWyA6MLKNPTHPsidyPth+fCcrfnl2T6GV86YTnjTN4Id86fmF73VNnMbCCBeK3amklS2BiTugwcyx2bA65UtixdtdR8LgHe/5DQqJggDblgTk1hUWUNTRLFLBrgJ5lpsaza6Ho+UV4Ut4nYE5V+W/rn8RgHtfhJzpH02PVoXSbkRu2MUiR6s5bxU71ZkdAPcN0rwvn+76C6fD0AaX8Gls+DKZZrKzhOpJS4PMKq4ZObvDMUXalfAbv60XOWB2aWsw==
    DB_USERNAME: AgDllWkmQra/AkEZ+vHEhXF6edTyuo6ADyE7mN8mhB2CNr9xD8RKrQ+9TYAPMaLXKhHVpII2yHQMsx+NlojtpbI+aprLCwRbG+Ek98DXisHQacD4DH8FDM8F/bqJh32hRun/1sW8/Ps4O6shAaA+nIhwyYBrAmz5YIhP8XbreB3QitWwsyDeQQ2wAL2UtnlF3GlWhZ3Bv2jBcndECOOW8yjHzJ3iSZwyU7lmLqI6uZZNnd3BQnpuqAVjHUS1Y0PfJLk3CKO7p22cYDZwfvV6cA+DihvzBSneoNWdYJUGnuE3LKQ2y4GY6Gr/KlGHlyqmVIi3dPF9lANPR+vUte123zMzA8uFqYsQ8lTmPQucmKMG9XyNfq2PN2HrcqRvFEK6iLX5h0LqfnG16k3UfY1pIhfWveiD07pJLplhrYKfJEsgLvnDBxEd7m9gegGRTQfN0HtcaWPNRoBHTjou7KNfQkTNAi1+gxKXGeZjgF63qU3W5g0t9JKykzhhJiLCmV+ChTLfqRxLYUuULsUOt36n21SRrXie7leylTLekj++d8FADmVVm5dEeuu9z9fmUd6xh0f8TR33n5Xpc9iJkJuCKY8Zskl+dTKjxiDVWz0ndaKAlzO6GIYXojvgP373+ETrx0yx932pZ+6k8DT/5Y6DcTjecv+7ZDH/JKzt+JcciKtkBC69LeQ/H/YTLVEIkwdDjUCSw0KXFm5d+TelCxESy6uHNSVerc7ocEGScpkLZu8JyA==
  template:
    metadata:
      name: immich-postgres-credentials
      namespace: immich
